project:
  type: website
  output-dir: _site
  execute-dir: project

engine: knitr

website:
  title: "gallery"
  favicon: cover.png
  repo-url: https://github.com/Yunuuuu/ggalign-gallery
  repo-branch: main
  repo-actions: ["source", "edit", "issue"]
  reader-mode: true
  twitter-card: true
  navbar:
    search: true
    logo: "cover.png"
    logo-alt: ggalign
    left:
      - text: Basics
        href: basics.qmd

    tools:
      - icon: code-square
        text: ggalign repo
        href: https://github.com/Yunuuuu/ggalign
      - icon: journal-text
        text: ggalign reference
        href: https://yunuuuu.github.io/ggalign
      - icon: book
        text: ggalign tutorial
        href: https://yunuuuu.github.io/ggalign-book
      - icon: layout-text-sidebar-reverse
        text: ggalign manuscript
        href: https://www.biorxiv.org/content/10.1101/2025.02.06.636847v1

bibliography: references.bib

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>"

format:
  html:
    theme:
      light: [cosmo, scss/light.scss]
      dark: [cosmo, scss/dark.scss]
    respect-user-color-scheme: true
    code-link: true
    code-annotations: hover
    mermaid:
      theme: default
