project:
  type: website
  output-dir: _site
  execute-dir: project

engine: knitr

website:
  title: gallery
  favicon: cover.png
  site-url: https://yunuuuu.github.io/ggalign-gallery/
  repo-url: https://github.com/Yunuuuu/ggalign-gallery
  repo-branch: main
  repo-actions: ["source", "edit", "issue"]
  reader-mode: true
  twitter-card: true
  open-graph:
    title: ggalign gallery

  comments:
    giscus: 
      repo: Yunuuuu/ggalign-gallery
      repo-id: R_kgDOPU41Yg
      category: Announcements
      category-id: DIC_kwDOPU41Ys4CtmMQ
      reactions-enabled: true
      loading: lazy
      theme:
        light: light # giscus theme used for light website theme
        dark: dark   # giscus theme used for dark website theme

  navbar:
    search: true
    logo: "cover.png"
    logo-alt: ggalign
    left:
      - text: Basics
        href: basics.qmd
      - text: Advanced
        href: advanced.qmd
      - text: Real World Data
        href: real-world-data.qmd

    tools:
      - icon: journal-text
        text: ggalign reference
        href: https://yunuuuu.github.io/ggalign
      - icon: book
        text: ggalign tutorial
        href: https://yunuuuu.github.io/ggalign-book
      - icon: layout-text-sidebar-reverse
        text: ggalign manuscript
        href: https://www.biorxiv.org/content/10.1101/2025.02.06.636847v1
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/Yunuuuu/ggalign-gallery
          - text: Report a Bug
            href:  https://github.com/Yunuuuu/ggalign-gallery/issues
          - text: ggalign repo
            href:  https://github.com/Yunuuuu/ggalign

bibliography: references.bib

date: last-modified

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>"

format:
  html:
    theme:
      light: [cosmo, scss/light.scss]
      dark: [cosmo, scss/dark.scss]
    respect-user-color-scheme: true
    code-link: true
    include-after-body: stats.html
    code-annotations: hover
    mermaid:
      theme: default
