project:
  type: website
  output-dir: _site
  execute-dir: project

engine: knitr

website:
  title: "ggalign Gallery"
  favicon: cover.png
  repo-url: https://github.com/Yunuuuu/ggalign-gallery
  repo-branch: main
  repo-actions: ["source", "edit", "issue"]
  code-links:
    - text: ggalign repo
      icon: code-square
      href: https://github.com/Yunuuuu/ggalign
  other-links:
    - text: ggalign reference
      icon: journal-text
      href: https://yunuuuu.github.io/ggalign
    - text: ggalign tutorial
      icon: journal-text
      href: https://yunuuuu.github.io/ggalign-book
    - text: ggalign manuscript
      icon: layout-text-sidebar-reverse
      href: https://www.biorxiv.org/content/10.1101/2025.02.06.636847v1
  reader-mode: true
  twitter-card: true
  navbar:
    search: true
    left:
      - text: Basics
        href: basics.qmd

bibliography: references.bib

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>"

format:
  html:
    theme: cosmo
    code-link: true
    code-annotations: hover
    mermaid:
      theme: default
