# Ranking of programming languages

```{r}
#| code-fold: true
library(ggalign)
```

```{r}
data <- data.frame(
    `Programming Language` = c(
        "Python",
        "C++",
        "C",
        "Java",
        "C#",
        "JavaScript",
        "Visual Basic",
        "Go",
        "Perl",
        "Delphi/Object Pascal",
        "Fortran",
        "SQL",
        "Ada",
        "R",
        "PHP"
    ),
    "Ratings" = c(
        26.14, 9.18, 9.03, 8.59, 5.52,
        3.15, 2.33, 2.11, 2.08, 1.82,
        1.75, 1.72, 1.52, 1.37, 1.27
    ),
    images <- c(
        "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1200px-Python-logo-notext.svg.png",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/1822px-ISO_C%2B%2B_Logo.svg.png",
        "https://upload.wikimedia.org/wikipedia/commons/1/19/C_Logo.png",
        "https://static-00.iconduck.com/assets.00/java-icon-1511x2048-6ikx8301.png",
        "https://upload.wikimedia.org/wikipedia/commons/4/4f/Csharp_Logo.png",
        "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/VB.NET_Logo.svg/2048px-VB.NET_Logo.svg.png",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Go_gopher_favicon.svg/2048px-Go_gopher_favicon.svg.png",
        "https://upload.wikimedia.org/wikipedia/commons/6/6e/Perl_programming_language_logo.svg",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Delphi_Logo.svg/2048px-Delphi_Logo.svg.png",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Fortran_logo.svg/2048px-Fortran_logo.svg.png",
        "https://upload.wikimedia.org/wikipedia/commons/4/44/SQL_%D0%BB%D0%BE%D0%B3%D0%BE%D1%82%D0%B8%D0%BF.png",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Ada_programming_language_logo.svg/1200px-Ada_programming_language_logo.svg.png",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/R_logo.svg/1200px-R_logo.svg.png",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/PHP-logo.svg/1200px-PHP-logo.svg.png"
    )
)
```

```{r}
stack_discreteh() +
    ggalign(data) +
    geom_magick()
```
